BuyandBye_project/base/urls.py
from django.urls import path

from . import views

# NOTE: only one views per url

urlpatterns = [
    path("", views.home, name="homepage"),
    # The about page view
    path("about/", views.aboutus, name="about"),
    # The Privacy policy page
    path("privacy_policy/", views.privacy_policy, name="privacy-policy"),
    # terms and conditions
    path(
        "terms_and_conditions/", views.terms_and_conditions, name="terms-and-conditions"
    ),
]

BuyandBye_project/buyandbye/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    # admin
    path("admin/", admin.site.urls),
    # base
    path("", include("base.urls")),
    # product
    path("", include("product.urls")),
    # users
    path("", include("users.urls")),
    # newsletter
    path(
        "newsletters/",
        include(("newsletters.urls", "newsletters"), namespace="newsletter"),
    ),
    # hitcount
    # django 3.0 doesnt support python_2_unicode so remove import and decorator from hitcount source file model
    path("hitcount/", include(("hitcount.urls", "hitcount"), namespace="hitcount")),
    # allauth
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:  # for development stage
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BuyandBye_project/product/urls.py
from django.urls import path
from hitcount.views import HitCountDetailView

from .views import category_views
from .views.category_views import CategoryDetailView, CategoryListView, load_subCat
from .views.item_views import (
    ItemCreateView,
    ItemDeleteView,
    ItemDetailView,
    ItemUpdateView,
    PopularItemListView,
    RecentItemListView,
    RecommendedItemListView,
    UserItemListView,
)
from .views.search_views import AdvancedSearchListView, SearchItemListView

# NOTE: only one views per url

urlpatterns = [
    # The product item view
    path("recent/", RecentItemListView.as_view(), name="recent-items"),
    path("popular/", PopularItemListView.as_view(), name="popular-items"),
    path("recommended/", RecommendedItemListView.as_view(), name="recommended-items"),
    # The individual user item view
    path("user/<str:username>", UserItemListView.as_view(), name="user-item"),
    # category page
    path("category/", CategoryListView.as_view(), name="category"),
    # The new item post creation view
    path("item/new", ItemCreateView.as_view(), name="item-create"),
    # The individual item's detailed view
    path("item/<slug:slug>", ItemDetailView.as_view(), name="item-detail"),
    path("category/<slug:slug>", CategoryDetailView.as_view(), name="category-detail"),
    # The existing item update view
    path("item/<slug:slug>/update", ItemUpdateView.as_view(), name="item-update"),
    # The existing item delete view
    path("item/<slug:slug>/delete", ItemDeleteView.as_view(), name="item-delete"),
    # The search results view
    path("search/", SearchItemListView.as_view(), name="search_results"),
    path(
        "search/advanced",
        AdvancedSearchListView.as_view(),
        name="advanced_search_results",
    ),
    path(
        "ajax/load_subcategory/",
        category_views.load_subCat,
        name="ajax-load-subcategory",
    ),
]

BuyandBye_project/product/models.py
"""MODEL for the Products including Category and Subcategory"""
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_extensions.db.fields import AutoSlugField
from djmoney.models.fields import MoneyField
from hitcount.models import HitCount
from PIL import Image

from .options import (
    CATEGORY_CHOICES,
    CONDITION_CHOICES,
    ITEM_CONTRACT_CHOICES,
    SUB_CATEGORY_CHOICES,
)


class Category(models.Model):
    """ Item Category Class"""

    name = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    slug = AutoSlugField(populate_from=["name"])
    image = models.ImageField(blank=True, null=True)
    illustration = models.ImageField(blank=True, null=True)
    icon = models.ImageField(blank=True, null=True)

    class Meta:
        """additional properties class"""

        ordering = ("name",)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.get_name_display()

    def get_absolute_url(self):
        return reverse("category-detail", kwargs={"slug": self.slug})


class SubCategory(models.Model):
    """ SubCategory class"""

    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subname = models.CharField(max_length=100, choices=SUB_CATEGORY_CHOICES)
    slug = AutoSlugField(populate_from=["subname"])
    image = models.ImageField(blank=True, null=True)
    illustration = models.ImageField(blank=True, null=True)
    icon = models.ImageField(blank=True, null=True)

    class Meta:
        """additional properties class"""

        # ordering = ('subname',)
        verbose_name = "Sub_Category"
        verbose_name_plural = "Sub_Categories"

    def __str__(self):
        # return self.subname returns the non human readable tuple
        return self.get_subname_display()  # returns human readable tuple


class Item(models.Model):
    """ Item class"""

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    price = MoneyField(decimal_places=2, max_digits=10, default_currency="NPR")
    content = models.TextField()
    image = models.ImageField(
        upload_to="item_pics/", blank=False, null=False
    )  # setting image
    image2 = models.ImageField(
        upload_to="item_pics/", blank=True, null=True
    )  # setting image
    image3 = models.ImageField(
        upload_to="item_pics/", blank=True, null=True
    )  # setting image
    image4 = models.ImageField(
        upload_to="item_pics/", blank=True, null=True
    )  # setting image
    image5 = models.ImageField(
        upload_to="item_pics/", blank=True, null=True
    )  # setting image
    image6 = models.ImageField(
        upload_to="item_pics/", blank=True, null=True
    )  # setting image
    condition = models.CharField(
        max_length=100, null=True, blank=True, choices=CONDITION_CHOICES
    )
    price_negotiability = models.BooleanField(default=False, blank=False)
    item_available_for = models.CharField(
        max_length=100, default="Sale", choices=ITEM_CONTRACT_CHOICES
    )
    sold = models.BooleanField(default=False)

    hit_count_generic = GenericRelation(
        HitCount,
        object_id_field="object_pk",
        related_query_name="hit_count_generic_relation",
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    slug = AutoSlugField(populate_from=["title"])

    # if image:
    #     def save(self, *args, **kwargs):
    #         # accessing parent class save function
    #         super(Item, self).save(*args, **kwargs)
    #         img = Image.open(self.image.path)
    #         if img.height > 3000 or img.width > 3000:
    #             output_size = (300, 300)
    #             img.thumbnail(output_size)
    #             img.save(self.image.path)  # overriding previous image

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("item-detail", kwargs={"slug": self.slug})

BuyandBye_project/product/views/category_views.py
""" VIEWS for product """

from django.contrib.auth.models import User, AnonymousUser
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (DetailView, ListView)
from django.db.models import Q
# local
from product.models import Category, SubCategory, Item
from activity.utils import create_action


"""------------------------------------------------------READ------------------------------------------------------"""


class CategoryListView(ListView):
    """ Category List using Django View: ListView """
    model = Category
    template_name = 'product/category/category_page.html'  # app/model_viewtype.html
    context_object_name = 'categorylist'
    ordering = ['name']


class CategoryDetailView(DetailView):
    """ Category Detail using Django View: DetailView """
    model = Category
    template_name = 'product/category/category_detail.html'
    context_object_name = 'category_item'

    def create_activity(self):
        category_id = self.object
        create_action(self.request.user, 'Browsed category', category_id)

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        cat_name = self.object.name
        if self.request.user.id is not None:
            self.create_activity()

        context.update({
            'cat_item': Item.objects.filter(Q(category__name=cat_name))
        })
        return context


"""------------------------------------------------------LOAD------------------------------------------------------"""


def load_subCat(request):
    """ Funcion for loading subcategories based on parent_category """
    category_id = request.GET.get('category')
    sub_categories = SubCategory.objects.filter(
        parent_category_id=category_id).order_by('subname')
    context = {
        'sub_categories': sub_categories
    }
    return render(request, 'product/category/subCat_dropdown_list_options.html', context)

BuyandBye_project/product/views/item_views.py
""" ITEM VIEWS """

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.contrib.auth.models import User, AnonymousUser
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

# local
from hitcount.views import HitCountDetailView
from product.forms import ItemCreateForm
from product.models import Item
from recommender.utils import recommend, user_recommend
from activity.utils import create_action


"""------------------------------------------------------CREATE------------------------------------------------------"""


class ItemCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """ Product Item Creation using Django View: CreateView"""

    model = Item
    form_class = ItemCreateForm
    template_name = "product/items/items_form.html"
    # fields = ['title', 'category', 'sub_category',
    #           'price', 'condition', 'content', 'image', ]
    success_message = f"Item was succesfully created."
    # success_url = reverse_lazy('item-detail') #success url not required for CreateView and UpdateView

    def create_activity(self):
        print("item history created")
        activity = create_action(self.object.author, "Posted item", self.object)
        return activity

    def form_valid(self, form):
        form.instance.author = self.request.user
        self.object = form.save()
        self.create_activity()
        return super(ItemCreateView, self).form_valid(form)

    # def save(self):
    #     super().save()
    #     self.create_activity()


"""------------------------------------------------------READ------------------------------------------------------"""


class RecentItemListView(ListView):
    """ Recent Product List using Django View: ListView"""

    model = Item
    template_name = "product/list_view/item_list.html"  # app/model_viewtype.html
    context_object_name = "item"
    ordering = ["-date_posted"]
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(RecentItemListView, self).get_context_data(**kwargs)
        context.update({"title": "Recent Items"})
        return context


class PopularItemListView(ListView):
    """ Popular Product List using Django View: ListView """

    model = Item
    template_name = "product/list_view/item_list.html"  # app/model_viewtype.html
    context_object_name = "item"
    ordering = ["-hit_count_generic__hits"]
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(PopularItemListView, self).get_context_data(**kwargs)
        context.update({"title": "Popular Items"})
        return context


class RecommendedItemListView(ListView):
    """ Popular Product List using Django View: ListView """

    model = Item
    template_name = "product/list_view/item_list.html"  # app/model_viewtype.html
    context_object_name = "item"
    ordering = ["-date_posted"]

    def get_context_data(self, **kwargs):
        context = super(RecommendedItemListView, self).get_context_data(**kwargs)
        user = self.request.user

        try:
            # if user.id is not None:
            rec_item = user_recommend(user)
        except:
            try:
                rec_item = user_recommend(1)
            except:
                rec_item = []

        context.update(
            {
                "title": "Recommended Items",
                "item": Item.objects.filter(id__in=rec_item),
            }
        )
        return context


class UserItemListView(ListView):
    """ Particular User's Posted Product List using Django View: ListView """

    model = Item
    template_name = "product/items/user_item.html"  # app/model_viewtype.html
    context_object_name = "user_items"
    paginate_by = 10

    def get_queryset(self):  # filtering based on username
        user = get_object_or_404(User, username=self.kwargs.get("username"))
        return Item.objects.filter(author=user).order_by("-date_posted")

    def get_context_data(self, **kwargs):
        context = super(UserItemListView, self).get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs.get("username"))

        context.update(
            {
                "title": f"Items by {user}",
                "user": user,
                "user_items": Item.objects.filter(author=user).order_by("-date_posted"),
            }
        )
        return context


class ItemDetailView(HitCountDetailView):
    """ Individual Product Deatil using Django View: DetailView """

    model = Item
    template_name = "product/items/items_detail.html"
    # hit count when set to true
    context_object_name = "item_detail"
    count_hit = True

    def create_activity(self):
        item_id = self.object
        # print(item_id.title)
        if self.request.user:
            create_action(self.request.user, "Viewed item", item_id)

    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data(**kwargs)

        if self.request.user.id is not None:
            self.create_activity()

        reco_item_id = recommend(self.object.id, 5)

        context.update(
            {
                "popular_items": Item.objects.order_by("-hit_count_generic__hits")[:5],
                "recommended_items": Item.objects.filter(id__in=reco_item_id),
            }
        )
        return context


"""------------------------------------------------------UPDATE------------------------------------------------------"""


class ItemUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """ Individual Product Update using Django View: UpdateView """

    model = Item
    form_class = ItemCreateForm
    template_name = "product/items/items_form.html"
    # fields = ['title', 'category', 'sub_category',
    #           'price', 'condition', 'content', 'image', ]

    def create_activity(self):
        item_id = self.object
        activity = create_action(self.object.author, "Updated item", item_id)
        return activity

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        self.create_activity()
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


"""------------------------------------------------------DELETE------------------------------------------------------"""


class ItemDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """ Individual Product Delete using Django View: DeleteView """

    model = Item
    template_name = "product/items/items_confirm_delete.html"
    success_url = "/"

    def test_func(self):
        item = self.get_object()
        if self.request.user == item.author:
            return True
        return False

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        # history creation
        item_id = self.object
        create_action(self.request.user, "Deleted item", item_id)
        print("item deleted")
        return super(ItemDeleteView, self).delete(*args, **kwargs)

BuyandBye_project/templates/product/items/items_confirm_delete.html
{% extends "base.html" %}

{% block mainbody %}

<div class="card justify-content-center">
     <div class="container justify-content-center">
          <form method="POST" class="justify-content-center">
               {% csrf_token %}
               <fieldset class="form-group bg-light">
                    <legend class="border-bottom mb-4">
                         Delete Post
                    </legend>
                    <h5>
                         Do you want to detele item post: <b> {{ object.title }} </b>?
                    </h5>
                    <div class="form-group">
                         <button class="btn btn-danger" type="submit">Yes, Delete</button>
                         <a class="btn btn-secondary" href="{% url 'item-detail' object.id %}">Cancel</a>
                    </div>
               </fieldset>
          </form>
     </div>
</div>

{% endblock mainbody %}

BuyandBye_project/templates/product/items/items_detail.html
{% extends "base.html" %}
{% load hitcount_tags %}

{% block content %}
<div class="wrapper">
    <div class="grid1">
        <div class="sidecard-specifications">
            {% include 'widget/item_specification.html' %}
            {% include 'widget/seller_card.html' %}
        </div>
    </div>

    <div class="grid2">
        <div class="card">
            <div class="card-title px-2 pt-4">
                <h4>{{object.title}}</h4>
            </div>
            <div class="card-body">
                <div>
                    <img src="{{object.image.url}}" alt="">
                </div>
                <br>
                <p>
                    <h4>Description</h4><br>
                    {{object.content}}
                </p>
            </div>
        </div>
    </div>

</div>

<div class="wrapper2">
    <div class="grid2">
        <div class="mb-5">
            <legend>Recommended items based on {{object.title}}</legend>
            {% for item in recommended_items %}
            {% include 'widget/item_card_list.html' %}
            {% endfor %}
        </div>

        <div>
            <legend>Popular items</legend>
            {% for item in popular_items %}
            {% include 'widget/item_card_list.html' %}
            {% endfor %}
        </div>
    </div>

    <div class="grid1">
        <div class="sticky top-15vh">
            <legend class="mb-4">
                <h4>Post Comments</h4>
            </legend>
            <div class="card" id="disqus_comment">
                <div class="card-body pt-3">
                    <div id="disqus_thread"></div>
                    <script>
                        /**
                         *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                         *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
                         */
                        /*
                        var disqus_config = function () {
                            this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                            this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                        };
                        */
                        (function () { // DON'T EDIT BELOW THIS LINE
                            var d = document,
                                s = d.createElement('script');

                            s.src = 'https://buyandbye-com-np.disqus.com/embed.js';

                            s.setAttribute('data-timestamp', +new Date());
                            (d.head || d.body).appendChild(s);
                        })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript"
                            rel="nofollow">comments
                            powered by Disqus.</a>
                    </noscript>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

BuyandBye_project/templates/product/items/items_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block mainbody %}
<legend>
     <h1>
          Post Item
     </h1>
</legend>

<div class="card">
     <div class="card-body">
          <form method="POST" id="itemForm" data-subcategory-url="{% url 'ajax-load-subcategory' %}" novalidate
               enctype="multipart/form-data">
               {% csrf_token %}
               <fieldset class="form-group">
                    <div class="container px-5 pt-auto form_sizer">
                         {% comment %} {{form|crispy}} {% endcomment %}
                         <div>
                              <div class="row">
                                   <div class="col-md">
                                        {{ form.category| as_crispy_field}}
                                   </div>
                                   <div class="col-md">
                                        {{ form.sub_category| as_crispy_field}}
                                   </div>
                              </div>
                              <div class="col-md">
                                   {{ form.title| as_crispy_field}}
                              </div>
                              <div class="row">
                                   <div class="col-md">
                                        {{ form.price| as_crispy_field}}
                                        {{ form.price_negotiability| as_crispy_field}}
                                   </div>
                              </div>
                              <div class="row justify-content-center">
                                   <div class="col-md-4">
                                        {{ form.item_available_for| as_crispy_field}}
                                   </div>
                              </div>
                              <div>
                                   {{ form.content| as_crispy_field}}
                              </div>
                              <div class="row">
                                   <div class="col-md">
                                        {{ form.image| as_crispy_field}}
                                   </div>
                                   <div class="col-md">
                                        {{ form.image2| as_crispy_field}}
                                   </div>
                                   <div class="col-md">
                                        {{ form.image3| as_crispy_field}}
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md">
                                        {{ form.image4| as_crispy_field}}
                                   </div>
                                   <div class="col-md">
                                        {{ form.image5| as_crispy_field}}
                                   </div>
                                   <div class="col-md">
                                        {{ form.image6| as_crispy_field}}
                                   </div>
                              </div>
                         </div>


                         <div class="form-group">
                              <button class="btn btn-info" type="submit">
                                   Post
                              </button>
                         </div>
                    </div>
               </fieldset>
          </form>
     </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
     $("#id_category").change(function () {
          var url = $("#itemForm").attr("data-subcategory-url"); // get the url of the `load_cities` view
          var categoryId = $(this).val(); // get the selected country ID from the HTML input

          $.ajax({ // initialize an AJAX request
               url: url, // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
               data: {
                    'category': categoryId // add the country id to the GET parameters
               },
               success: function (data) { // `data` is the return of the `load_cities` view function
                    $("#id_sub_category").html(
                         data
                    ); // replace the contents of the city input with the data that came from the server
               }
          });

     });
</script>

{% endblock mainbody %}

BuyandBye_project/templates/product/items/user_item.html
{% extends "base.html" %}

{% block wrapper %}
<div class="wrapper">

	<div class="grid1">
		{% block sidebar %}
		<div class="sticky" style="top: 15vh">
			{% include 'widget/user_info.html' %}
		</div>
		{% endblock sidebar %}
	</div>

	<div class="grid2">
		{% block content %}
		<h4 style="align-content:center; " class="mb-5">Items ({{ page_obj.paginator.count }})</h4>


		{% for item in user_items %}
		{% include 'widget/item_card_list.html' %}
		{% endfor %}

		<!-- Checks if pages available -->
		{% if is_paginated %}
		{% include 'widget/item_pagination.html' %}
		{% endif %}
		<!-- /Checks if pages available -->

		{% endblock content %}
	</div>

</div>
{% endblock wrapper %}

BuyandBye_project/templates/product/items/user_recommended_item.html
{% block user_recommended %}
{% comment %} {% if user is not None %} {% endcomment %}
<div class="container bg-" id="Recent_Item">
    <div class="row justify-content-center">
        <legend>
            <a href="#Recommended_Item">
                Recommended Items For You
            </a>
        </legend>
    </div>

    {% for items in rec_item %}
    <div class="d-inline-flex p-2 bd-highlight align-items-center bg-">
        <div class="card card-item-grid text-center">
            <img src="{{items.image.url}}" alt="" class="card-img-top img-item-grid-cover">
            <span class="badge badge-danger badge-header-category">{{items.category}}</span>
            <div class="card-body">
                <a href="{% url 'item-detail' items.slug %}" title="{{ items.title }}" class="card-title text-primary">
                    {{ items.title }}
                </a>
                <p class="card-subtitle card-subtitle-price" title="{{ items.price }}">
                    <b>{{items.price}}</b>
                </p>
                <p class="card-subtitle card-subtitle-condition" title="{{ items.condition }}">
                    {{items.condition}}
                </p>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="row justify-content-center">
        <a href="{% url 'recommended-items' %}" class="btn btn-primary">View More</a>
    </div>

</div>

{% endblock user_recommended %}