BuyandBye_project/base/urls.py
from django.urls import path

from . import views

# NOTE: only one views per url

urlpatterns = [
    path("", views.home, name="homepage"),
    # The about page view
    path("about/", views.aboutus, name="about"),
    # The Privacy policy page
    path("privacy_policy/", views.privacy_policy, name="privacy-policy"),
    # terms and conditions
    path(
        "terms_and_conditions/", views.terms_and_conditions, name="terms-and-conditions"
    ),
]

BuyandBye_project/buyandbye/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    # admin
    path("admin/", admin.site.urls),
    # base
    path("", include("base.urls")),
    # product
    path("", include("product.urls")),
    # users
    path("", include("users.urls")),
    # newsletter
    path(
        "newsletters/",
        include(("newsletters.urls", "newsletters"), namespace="newsletter"),
    ),
    # hitcount
    # django 3.0 doesnt support python_2_unicode so remove import and decorator from hitcount source file model
    path("hitcount/", include(("hitcount.urls", "hitcount"), namespace="hitcount")),
    # allauth
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:  # for development stage
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BuyandBye_project/newsletters/urls.py
from django.urls import include, path

from .views import control_newsletter, newsletter_signup, newsletter_unsubscribe

urlpatterns = [
    path("subscribe/", newsletter_signup, name="newsletter_signup"),
    path("unsubscribe/", newsletter_unsubscribe, name="newsletter_unsubscribe"),
    path("control/", control_newsletter, name="control"),
]

BuyandBye_project/newsletters/models.py
from django.db import models


class NewsletterUser(models.Model):
    email = models.EmailField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class NewsLetter(models.Model):
    EMAIL_STATUS_CHOICES = (("Draft", "Draft"), ("Published", "Published"))
    subject = models.CharField(max_length=250)
    body = models.TextField()
    email = models.ManyToManyField(NewsletterUser)
    status = models.CharField(max_length=10, choices=EMAIL_STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

BuyandBye_project/newsletters/forms.py
from crispy_forms.helper import FormHelper
from django import forms

from .models import NewsLetter, NewsletterUser


class NewsletterSignUpForm(forms.ModelForm):
    class Meta:
        model = NewsletterUser
        fields = ["email"]

        def clean_email(self):
            email = self.cleaned_data.get("email")

            return email


class NewsletterCreationForm(forms.ModelForm):
    class Meta:
        model = NewsLetter
        fields = (
            "subject",
            "body",
            "email",
            "status",
        )

BuyandBye_project/newsletters/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives, send_mail
from django.shortcuts import render
from django.template.loader import get_template

from .forms import NewsletterCreationForm, NewsletterSignUpForm
from .models import NewsLetter, NewsletterUser


def newsletter_signup(request):
    form = NewsletterSignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            messages.warning(
                request,
                "This email exists already in our database",
                "alert alert-warning alert-dismissible",
            )
        else:
            instance.save()
            messages.success(
                request,
                "You have Subscribed to our Newsletter Service. Your email has been added to our database",
            )
            subject = "Thank you for joining our Newsletter"
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]
            with open(
                settings.BASE_DIR + "/templates/newsletters/subscribe_email.txt"
            ) as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(
                subject=subject, body=signup_message, from_email=from_email, to=to_email
            )
            html_template = get_template("newsletters/subscribe_email.html").render()
            message.attach_alternative(html_template, "text/html")
            message.send()
    context = {
        "form": form,
    }

    template = "newsletters/subscribe.html"
    return render(request, template, context)


def newsletter_unsubscribe(request):
    form = NewsletterSignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            NewsletterUser.objects.filter(email=instance.email).delete()
            messages.success(
                request,
                "Your email has been deleted from our database.",
                "alert alert-success alert-dismissible",
            )
            subject = "You have been unsubscribed"
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]
            with open(
                settings.BASE_DIR + "/templates/newsletters/unsubscribe_email.txt"
            ) as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(
                subject=subject, body=signup_message, from_email=from_email, to=to_email
            )
            html_template = get_template("newsletters/unsubscribe_email.html").render()
            message.attach_alternative(html_template, "text/html")
            message.send()
        else:
            messages.warning(
                request,
                "We dont have the email you entered in our database",
                "alert alert-warning alert-dismissible",
            )

    context = {
        "form": form,
    }

    template = "newsletters/unsubscribe.html"
    return render(request, template, context)


def control_newsletter(request):
    form = NewsletterCreationForm(request.POST or None)

    if form.is_valid():
        instance = form.save()
        newsletter = NewsLetter.objects.get(id=instance.id)
        if newsletter.status == "Published":
            subject = newsletter.subject
            body = newsletter.body
            from_email = settings.EMAIL_HOST_USER
            for email in newsletter.email.all():
                print(email)
                send_mail(
                    subject=subject,
                    from_email=from_email,
                    recipient_list=[email.email],
                    message=body,
                    fail_silently=True,
                )

    context = {
        "form": form,
    }

    template = "newsletters/control_newsletter.html"
    return render(request, template, context)

BuyandBye_project/templates/newsletters/control_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Dashboard Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
{% comment %} <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c"> {% endcomment %}


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>
        <div>
        {% block content %}
        {% endblock %}
        <div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="dashboard.js"></script></body>
</html>

BuyandBye_project/templates/newsletters/control_newsletter.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block mainbody %}
<div class="card category-card">
    <div class="container px-5">
        <div class="card-title mt-5">
            <h1 class="h2">Dashboard</h1>
        </div>
        <hr>
        <form method="POST">{% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-default">Save</button>
        </form>
    </div>
</div>

{% endblock mainbody %}

BuyandBye_project/templates/newsletters/subscribe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class= "container">
    <div class= "row">
        <div class="col-lg-6 col-lg-offset-3">
            <h6 class="text-center">Sign Up BuyandBye's Newsletter </h6>
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
                            {{ message }}
                    </div>      
                {% endfor %}
            {% else %} 
            <form method="POST">{% csrf_token %}
                <div class = "input-group">
                    {{ form|crispy }}
                    <span class ="input-group-btn">
                        <button class = "btn btn-default" type="submit">Subscribe</button>
                    </span>
                </div>    
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %} 

BuyandBye_project/templates/newsletters/subscribe_email.html
<html>
<head>
</head>
<body>
<h2>Welcome to BuyandBye's Newsletter </h2>
<p>Thank you for joining</p>
<p>To unsubcribe visit the following link : <a href = "{% url "newsletter:newsletter_unsubscribe" %}">unsubcribe</a></p>
</body>
</html>

BuyandBye_project/templates/newsletters/unsubscribe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class= "container">
    <div class= "row">
        <div class="col-lg-6 col-lg-offset-3">
            <h6 class="text-center">Sign Up BuyandBye's Newsletter </h6>
            <form method="POST">{% csrf_token %}
                <div class = "input-group">
                    {{ form|crispy }}
                    <span class ="input-group-btn">
                        <button class = "btn btn-default" type="submit">Unsubscribe</button>
                    </span>
                </div>    
            </form>
        </div>
    </div>
</div>
{% endblock content %} 

BuyandBye_project/templates/newsletters/unsubscribe_email.html
<html>
<head>
</head>
<body>
<h2>Sorry to see you go</h2>
<p>byee byee</p>
</body>
</html>